Remove skip.tests from release.yml
ExpediaGroup/beekeeper pull request #94
Opened 2021-07-21 12:41 UTC by shermosa

Fixes #

2021-07-21 12:51 UTC, javsanbel2 approved these changes

2021-07-21 12:52 UTC, javsanbel2 commented
Update parent version

2021-07-22 08:13 UTC, patduin commented on pom.xml
> -
you need to update the parent pom still right

2021-07-22 08:14 UTC, patduin requested changes
blocked by: https://github.com/ExpediaGroup/eg-oss-parent/pull/19

2021-07-23 09:50 UTC, closed without merging